# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Cyber Pentest Review

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.STORM_TOKEN }}
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 autoflake
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Auto Cleanup (Remove Unused Imports)
      run: |
        autoflake --in-place --remove-all-unused-imports --recursive .

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82,F401 --show-source --statistics
        
    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"       
        CHANGED_FILES=$(git status --porcelain | sed 's/^M //g' | tr '\n' ', ')       
        git add .
        
        if ! git diff --cached --quiet; then
          git commit -m "style: auto-cleanup imports in: ${CHANGED_FILES%, }"
          git push
        fi

    

        

