name: Auto Format with Black

on:
  push:
    branches: [ main ]

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.STORM_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Black
        run: pip install black

      - name: Run Black
        run: black .

      - name: Commit changes if any
        run: |
          git config --global user.name "black-style[bot]"
          git config --global user.email "storm[bot]@github.com"
          CHANGED_FILES=$(git status --porcelain | sed 's/^M //g' | tr '\n' ', ')
          git add .

          if ! git diff --cached --quiet; then
            git commit -m "Auto format with Black: ${CHANGED_FILES%, }"
            git push
          fi
